/**
 * Types + helpers for TRUE regeneration provenance flowing from the backend.
 *
 * Two shapes carry provenance:
 *   1. `candidate_update.mutation` when scope === "regenerate" (Helio
 *      `regenerate_region` tool) - see RegenerationMutation.
 *   2. `candidate.provenance` on WS pipeline_complete candidates (constrained
 *      full redesign) - see CandidateProvenance.
 *
 * HONESTY CONTRACT: the `engine` field is the ACTUAL engine used, and
 * `sampled_probs_are_real_model_confidence` gates whether `sampled_probs` are
 * genuine Evo 2 probabilities. The UI must never present mock output as real,
 * and must never render a confidence strip when the probs are absent/fake.
 */

export type RegenEngine = "nim" | "local" | "mock" | string;

export interface ConstraintReport {
  gc_target: number | null;
  achieved_gc: number;
  gc_within_tolerance: boolean;
  length_delta_requested: number;
  region_length_before: number;
  region_length_after: number;
  avoid_motifs: string[];
  avoid_motifs_still_present: string[];
  temperature: number;
  satisfied: boolean;
  note: string;
}

export interface RegenerationMutation {
  scope: "regenerate";
  mode: "regenerate_region";
  start: number;
  end: number;
  new_region_end: number;
  regenerated: string;
  regenerated_length: number;
  engine: RegenEngine;
  method: string;
  candidates_evaluated: number;
  elapsed_ms: number | null;
  prefix_only_conditioning: boolean;
  sampled_probs: number[] | null;
  sampled_probs_are_real_model_confidence: boolean;
  constraint_report: ConstraintReport;
}

/** Provenance dict carried by redesign candidates from pipeline_complete. */
export interface CandidateProvenance {
  engine: RegenEngine;
  method: string;
  mean_sampled_prob: number | null;
  sampled_probs_are_real_model_confidence: boolean;
  prefix_only_conditioning: boolean;
  constraint_report?: ConstraintReport | null;
}

/** Narrow an unknown mutation object to a regeneration mutation. */
export function isRegenerationMutation(
  mutation: unknown,
): mutation is RegenerationMutation {
  if (!mutation || typeof mutation !== "object") return false;
  const m = mutation as Record<string, unknown>;
  return (
    m.scope === "regenerate" &&
    typeof m.start === "number" &&
    typeof m.end === "number" &&
    typeof m.regenerated === "string"
  );
}

export interface EngineBadge {
  /** Short label, e.g. "Evo 2 · NIM (live)". */
  label: string;
  /** Whether this engine produced real model output (drives tone/colour). */
  isLive: boolean;
  /** Longer honest description for a tooltip. */
  detail: string;
}

/**
 * Map an engine string to an honest, user-facing badge. "nim" and "local" are
 * live Evo 2 engines; "mock" is the explicit offline test engine (EVO2_MODE=mock)
 * and is labeled as such. Anything unknown shows its raw engine string honestly.
 */
export function engineBadge(engine: RegenEngine): EngineBadge {
  switch (engine) {
    case "nim":
      return {
        label: "Evo 2 · NIM (live)",
        isLive: true,
        detail:
          "Generated by the live Evo 2 NIM endpoint. Per-base probabilities below are real model confidence.",
      };
    case "local":
      return {
        label: "Evo 2 · local weights",
        isLive: true,
        detail:
          "Generated by a locally hosted Evo 2 checkpoint. Per-base probabilities are real model confidence.",
      };
    case "mock":
      return {
        label: "Offline engine (not Evo 2)",
        isLive: false,
        detail:
          "Produced by the explicit offline test engine (EVO2_MODE=mock), not Evo 2. No real model confidence is available.",
      };
    default:
      return {
        label: `Evo 2 · ${engine}`,
        isLive: false,
        detail: `Engine reported as "${engine}". Treat confidence as unavailable unless flagged real.`,
      };
  }
}

/** Human-readable method label for the tooltip. */
export function methodLabel(method: string): string {
  if (!method) return "sampled candidates, picked best";
  if (method.includes("rejection_sampling")) {
    return "prefix-conditioned rejection sampling - sampled candidates, picked best";
  }
  return method.replace(/_/g, " ");
}

/**
 * Should we render a real per-base confidence strip? Only when the engine is
 * live AND the backend flagged the probabilities as real AND we actually have
 * a non-empty array. Guards every field so a missing/partial payload degrades
 * to the honest "no confidence" note rather than fabricating a strip.
 */
export function hasRealConfidence(
  m: Pick<
    RegenerationMutation,
    "engine" | "sampled_probs" | "sampled_probs_are_real_model_confidence"
  >,
): m is typeof m & { sampled_probs: number[] } {
  return (
    m.sampled_probs_are_real_model_confidence === true &&
    Array.isArray(m.sampled_probs) &&
    m.sampled_probs.length > 0 &&
    (m.engine === "nim" || m.engine === "local")
  );
}
